spring:
  application:
    name: weather-report
server:
  port: 8084
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
feign:
  client:
    config:
      feign-name:
        connection-timeout: 5000
        read-timeout: 5000
  hystrix:
    enabled: true